### ISSUE TITLE
Not all text is translatable

### ISSUE THREAD

**Issue by cpkio** [flagrow/mason#10]
I have made a russian translation of Mason, but some text labels are hardcoded: Field setting, Field answers, New answer :)

![2019-07-29_175814](https://user-images.githubusercontent.com/1917113/62058658-769ecd00-b22a-11e9-879c-ea6e5909abc8.jpg)

**Comment by clarkwinkelmann** [comment]
I can confirm.

I found the following texts missing translations.

https://github.com/flagrow/mason/blob/50b7050edd9f2e3d317caf70909f72d7a8c93c52/js/src/admin/components/FieldEdit.js#L68

https://github.com/flagrow/mason/blob/50b7050edd9f2e3d317caf70909f72d7a8c93c52/js/src/admin/components/FieldEdit.js#L164

https://github.com/flagrow/mason/blob/50b7050edd9f2e3d317caf70909f72d7a8c93c52/js/src/admin/components/FieldAnswersEdit.js#L88

https://github.com/flagrow/mason/blob/50b7050edd9f2e3d317caf70909f72d7a8c93c52/js/src/admin/components/AnswerEdit.js#L23

I'll look into it when I find some time, or PR welcome.
