### ISSUE TITLE
Page not loading after installing mason

### ISSUE THREAD

**Issue by Adaliciously** [flagrow/mason#6]
So recently I installed it with composer, after enabling it, everything stops working...
Tried clearing cache/ctrl+f5

Browser's console returns "TypeError: module is undefined" on line
      ``      if (module.default) module.default(app); ``

**Comment by luceos** [comment]
Sounds like js didn't even compile. Any errors in `storage/logs/flarum.log`?

**Comment by Adaliciously** [comment]
http://ttt.cayon.pl/flarum.log

Doesnt seem to be related...

**Comment by luceos** [comment]
Do you have cloudflare installed?

**Comment by Adaliciously** [comment]
Yes, I do.

**Comment by luceos** [comment]
Try flushing its cache or disabling it al together for a bit to see whether that helps. Also make sure to clear the cache of your browser and run `php flarum cache:clear` plus `rm -f assets/rev-manifest.json`

**Comment by Adaliciously** [comment]
Works now, thank you.
